Repository knative-extensions/net-certmanager, pull requests merged in 2020-10, with the labels that each got.

#84 [Automated] Update actions
  .github/workflows/knative-style.yaml
Labels: approved, cla: yes, lgtm, size/XS

#86 [Automated] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/client/injection/reconciler/networking/v1alpha1/certificate/controller.go
  vendor/knative.dev/networking/pkg/client/injection/reconciler/networking/v1alpha1/certificate/reconciler.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#88 [Automated] Update actions
  .github/workflows/knative-style.yaml
Labels: approved, cla: yes, lgtm, size/S

#87 [Automated] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/ingress_types.go
  vendor/knative.dev/pkg/apis/contexts.go
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/knative.dev/pkg/metrics/resource_view.go
  vendor/knative.dev/test-infra/scripts/library.sh
  vendor/knative.dev/test-infra/scripts/markdown-link-check-config.rc
  vendor/knative.dev/test-infra/scripts/markdown-lint-config.rc
  vendor/knative.dev/test-infra/scripts/presubmit-tests.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#92 [Automated] Update actions
  .github/workflows/knative-boilerplate.yaml
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-security.yaml
  .github/workflows/knative-style.yaml
Labels: approved, cla: yes, lgtm, size/M

#96 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/knative.dev/pkg/metrics/memstats.go
  vendor/knative.dev/pkg/test/logstream/interface.go
  vendor/knative.dev/pkg/test/logstream/v2/interface.go
  vendor/knative.dev/pkg/test/logstream/v2/stream.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#98 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/test/clients.go
  vendor/knative.dev/networking/test/conformance/certificate/utils.go
  vendor/knative.dev/networking/test/util.go
  vendor/knative.dev/pkg/configmap/store.go
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/knative.dev/pkg/metrics/config_observability.go
  vendor/knative.dev/pkg/metrics/stackdriver_exporter.go
  vendor/knative.dev/pkg/test/clients.go
  vendor/knative.dev/pkg/test/ingress/ingress.go
  vendor/knative.dev/pkg/test/kube_checks.go
  vendor/knative.dev/pkg/test/logstream/interface.go
  vendor/knative.dev/pkg/test/monitoring/doc.go
  vendor/knative.dev/pkg/test/monitoring/monitoring.go
  vendor/knative.dev/pkg/test/spoof/spoof.go
  vendor/knative.dev/pkg/test/zipkin/doc.go
  vendor/knative.dev/pkg/test/zipkin/util.go
  vendor/knative.dev/pkg/tracing/config/tracing.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#99 [Automated] Update actions
  .github/workflows/knative-style.yaml
Labels: approved, cla: yes, lgtm, size/XS

#100 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/domain_types.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/ingress_types.go
  vendor/knative.dev/networking/pkg/network.go
  vendor/knative.dev/networking/test/e2e_constants.go
  vendor/knative.dev/networking/test/types/runtime.go
  vendor/knative.dev/pkg/configmap/testing/configmap.go
  vendor/knative.dev/pkg/metrics/config_observability.go
  vendor/knative.dev/test-infra/scripts/library.sh
  vendor/knative.dev/test-infra/scripts/shellcheck-presubmit.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#101 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/apis/duck/README.md
  vendor/knative.dev/pkg/apis/field_error.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/pkg/controller/two_lane_queue.go
  vendor/knative.dev/pkg/hash/doc.go
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/knative.dev/pkg/kmeta/ownerrefable_accessor.go
  vendor/knative.dev/pkg/leaderelection/context.go
  vendor/knative.dev/pkg/logging/config.go
  vendor/knative.dev/pkg/metrics/exporter.go
  vendor/knative.dev/pkg/network/network.go
  vendor/knative.dev/pkg/test/monitoring/doc.go
  vendor/knative.dev/pkg/test/spoof/spoof.go
  vendor/knative.dev/pkg/test/tinterface.go
  vendor/knative.dev/pkg/webhook/stats_reporter.go
  vendor/knative.dev/pkg/webhook/webhook.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#102 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/client/injection/reconciler/networking/v1alpha1/certificate/reconciler.go
  vendor/knative.dev/networking/test/util.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#103 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/test/conformance.go
  vendor/knative.dev/networking/test/crd.go
  vendor/knative.dev/networking/test/e2e_constants.go
  vendor/knative.dev/networking/test/prober.go
  vendor/knative.dev/networking/test/util.go
  vendor/knative.dev/pkg/injection/config.go
  vendor/knative.dev/pkg/test/clients.go
  vendor/knative.dev/pkg/test/e2e_flags.go
  vendor/knative.dev/pkg/test/flags/e2e_flags.go
  vendor/knative.dev/pkg/test/logstream/interface.go
  vendor/knative.dev/pkg/test/logstream/null.go
  vendor/knative.dev/pkg/test/logstream/v2/stream.go
  vendor/knative.dev/pkg/test/request.go
  vendor/knative.dev/pkg/test/tinterface.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#104 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/ingress_types.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/pkg/kmeta/names.go
  vendor/knative.dev/pkg/metrics/config.go
  vendor/knative.dev/pkg/reconciler/events.go
  vendor/knative.dev/pkg/test/clients.go
  vendor/knative.dev/pkg/test/logging/tlogger.go
  vendor/knative.dev/pkg/test/logstream/v2/stream.go
  vendor/knative.dev/pkg/test/request.go
  vendor/knative.dev/pkg/tracing/config/tracing.go
  vendor/knative.dev/test-infra/scripts/library.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#105 [Automated] Update actions
  .github/workflows/knative-releasability.yaml
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#106 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/test-infra/scripts/library.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#107 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/apis/networking/metadata_validation.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/serverlessservice_validation.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#108 [Automated] Update actions
  .github/workflows/knative-boilerplate.yaml
  .github/workflows/knative-donotsubmit.yaml
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-security.yaml
  .github/workflows/knative-stale.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#109 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/metrics/config.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#110 [Automated] Update actions
  .github/workflows/knative-releasability.yaml
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#111 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/logging/object_encoders.go
  vendor/knative.dev/pkg/metrics/config.go
  vendor/knative.dev/pkg/webhook/certificates/certificates.go
  vendor/knative.dev/pkg/webhook/configmaps/configmaps.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#112 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/client/injection/reconciler/networking/v1alpha1/certificate/reconciler.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/knative.dev/pkg/leaderelection/config.go
  vendor/knative.dev/pkg/leaderelection/context.go
  vendor/knative.dev/pkg/logging/config.go
  vendor/knative.dev/pkg/metrics/config.go
  vendor/knative.dev/pkg/test/zipkin/util.go
  vendor/knative.dev/pkg/tracing/config/tracing.go
  vendor/knative.dev/test-infra/scripts/library.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#113 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/k8s.io/apimachinery/pkg/api/apitesting/fuzzer/fuzzer.go
  vendor/k8s.io/apimachinery/pkg/api/apitesting/fuzzer/valuefuzz.go
  vendor/knative.dev/pkg/apis/duck/v1/fuzzer.go
  vendor/knative.dev/pkg/apis/testing/fuzzer/fuzzer.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#114 use the new hack repo for scripts
  go.mod
  go.sum
  hack/release.sh
  hack/tools.go
  hack/update-deps.sh
  test/e2e-common.sh
  test/presubmit-tests.sh
  vendor/knative.dev/hack/CODE_OF_CONDUCT.md
  vendor/knative.dev/hack/LICENSE
  vendor/knative.dev/hack/README.md
  vendor/knative.dev/hack/e2e-tests.sh
  vendor/knative.dev/hack/go.mod
  vendor/knative.dev/hack/hack.go
  vendor/knative.dev/hack/infra-library.sh
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/hack/performance-tests.sh
  vendor/knative.dev/hack/presubmit-tests.sh
  vendor/knative.dev/hack/release.sh
  vendor/knative.dev/hack/shellcheck-presubmit.sh
  vendor/knative.dev/networking/test/e2e-common.sh
  vendor/knative.dev/networking/test/presubmit-tests.sh
  vendor/knative.dev/pkg/hack/tools.go
  vendor/knative.dev/pkg/hack/update-codegen.sh
  vendor/knative.dev/pkg/hack/update-deps.sh
  vendor/knative.dev/pkg/hack/verify-codegen.sh
  vendor/knative.dev/pkg/logging/config.go
  vendor/knative.dev/pkg/test/presubmit-tests.sh
  vendor/knative.dev/pkg/test/test-reconciler-codegen.sh
  vendor/knative.dev/pkg/tracing/config/tracing.go
  vendor/knative.dev/test-infra/scripts/update-test-infra.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#115 [Automated] Update actions
  .github/workflows/knative-style.yaml
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#116 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  third_party/VENDOR-LICENSE/github.com/blang/semver/v4/LICENSE
  third_party/VENDOR-LICENSE/gopkg.in/evanphx/json-patch.v4/LICENSE
  vendor/github.com/blang/semver/.travis.yml
  vendor/github.com/blang/semver/README.md
  vendor/github.com/blang/semver/package.json
  vendor/github.com/blang/semver/v4/LICENSE
  vendor/github.com/blang/semver/v4/go.mod
  vendor/github.com/blang/semver/v4/json.go
  vendor/github.com/blang/semver/v4/range.go
  vendor/github.com/blang/semver/v4/semver.go
  vendor/github.com/blang/semver/v4/sort.go
  vendor/github.com/blang/semver/v4/sql.go
  vendor/gopkg.in/evanphx/json-patch.v4/.travis.yml
  vendor/gopkg.in/evanphx/json-patch.v4/LICENSE
  vendor/gopkg.in/evanphx/json-patch.v4/README.md
  vendor/gopkg.in/evanphx/json-patch.v4/errors.go
  vendor/gopkg.in/evanphx/json-patch.v4/merge.go
  vendor/gopkg.in/evanphx/json-patch.v4/patch.go
  vendor/knative.dev/pkg/apis/duck/patch.go
  vendor/knative.dev/pkg/configmap/parse.go
  vendor/knative.dev/pkg/signals/signal.go
  vendor/knative.dev/pkg/version/version.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, ok-to-test, size/XXL

#117 [release-0.18] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#118 Narrow down security context of the controller and webhook
  config/controller.yaml
  config/webhook-deployment.yaml
Labels: approved, cla: yes, lgtm, size/S

#120 [Automated] Update actions
  .github/workflows/knative-style.yaml
Labels: approved, cla: yes, lgtm, ok-to-test, size/S
