Repository knative-extensions/net-certmanager, pull requests merged in 2020-05, with the labels that each got.

#17 Revert "Add controller type filter everywhere and collapse code. (#77…
  pkg/reconciler/certificate/controller.go
Labels: approved, cla: yes, lgtm, size/S

#16 Add webhook for net-certmanager repo
  cmd/webhook/kodata/HEAD
  cmd/webhook/kodata/LICENSE
  cmd/webhook/kodata/VENDOR-LICENSE
  cmd/webhook/kodata/refs
  cmd/webhook/main.go
  config/500-validating-webhook.yaml
  config/500-webhook-secret.yaml
  config/webhook-deployment.yaml
  config/webhook-service.yaml
  vendor/knative.dev/pkg/client/injection/kube/informers/admissionregistration/v1beta1/validatingwebhookconfiguration/validatingwebhookconfiguration.go
  vendor/knative.dev/pkg/injection/clients/namespacedkube/informers/core/v1/secret/secret.go
  vendor/knative.dev/pkg/webhook/certificates/certificates.go
  vendor/knative.dev/pkg/webhook/certificates/controller.go
  vendor/knative.dev/pkg/webhook/configmaps/configmaps.go
  vendor/knative.dev/pkg/webhook/configmaps/controller.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/interface.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XL

#18 Fix update-codegen for the post-go-mod world.
  hack/update-codegen.sh
Labels: approved, cla: yes, lgtm, size/XS

#20 [RELEASE] Pin serving to 0.15.
  go.mod
  go.sum
  hack/update-deps.sh
  vendor/knative.dev/serving/pkg/apis/autoscaling/annotation_validation.go
  vendor/knative.dev/serving/pkg/apis/autoscaling/register.go
  vendor/knative.dev/serving/pkg/apis/autoscaling/v1alpha1/pa_lifecycle.go
  vendor/knative.dev/serving/pkg/apis/serving/k8s_lifecycle.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/revision_lifecycle.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/revision_types.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/route_lifecycle.go
  vendor/knative.dev/serving/pkg/apis/serving/v1alpha1/revision_types.go
  vendor/knative.dev/serving/pkg/apis/serving/v1alpha1/route_lifecycle.go
  vendor/knative.dev/serving/pkg/autoscaler/config/config.go
  vendor/knative.dev/serving/test/e2e-tests.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#21 [POST-RELEASE] Track master branches again.
  go.mod
  go.sum
  hack/update-deps.sh
  vendor/knative.dev/pkg/apis/duck/v1/status_types.go
  vendor/knative.dev/pkg/apis/duck/v1/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/apis/duck/v1beta1/status_types.go
  vendor/knative.dev/pkg/apis/duck/v1beta1/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/configmap/store.go
  vendor/knative.dev/pkg/logging/config
  vendor/knative.dev/pkg/logging/object_encoders.go
  vendor/knative.dev/pkg/test/spoof/spoof.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/configuration_types.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/revision_types.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/service_types.go
  vendor/knative.dev/test-infra/scripts/update-test-infra.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L
