Repository knative-extensions/net-certmanager, pull requests merged in 2020-06, with the labels that each got.

#22 Bump module to go1.14 & use vendored certificate conformance tests
  go.mod
  go.sum
  test/conformance/certificate_test.go
  test/e2e-tests.sh
  vendor/knative.dev/pkg/apis/duck/v1/status_types.go
  vendor/knative.dev/pkg/apis/duck/v1beta1/status_types.go
  vendor/knative.dev/pkg/configmap/parse.go
  vendor/knative.dev/pkg/hack/update-deps.sh
  vendor/knative.dev/pkg/hack/update-k8s-deps.sh
  vendor/knative.dev/pkg/kmeta/map.go
  vendor/knative.dev/pkg/webhook/webhook.go
  vendor/knative.dev/serving/pkg/apis/autoscaling/v1alpha1/metric_types.go
  vendor/knative.dev/serving/pkg/apis/autoscaling/v1alpha1/pa_lifecycle.go
  vendor/knative.dev/serving/pkg/apis/autoscaling/v1alpha1/pa_types.go
  vendor/knative.dev/serving/pkg/apis/autoscaling/v1alpha1/pa_validation.go
  vendor/knative.dev/serving/pkg/apis/config/defaults.go
  vendor/knative.dev/serving/pkg/apis/config/features.go
  vendor/knative.dev/serving/pkg/apis/config/store.go
  vendor/knative.dev/serving/pkg/apis/config/zz_generated.deepcopy.go
  vendor/knative.dev/serving/pkg/apis/networking/v1alpha1/ingress_types.go
  vendor/knative.dev/serving/pkg/apis/networking/v1alpha1/ingress_validation.go
  vendor/knative.dev/serving/pkg/apis/networking/v1alpha1/zz_generated.deepcopy.go
  vendor/knative.dev/serving/pkg/apis/serving/k8s_validation.go
  vendor/knative.dev/serving/pkg/apis/serving/metadata_validation.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/revision_defaults.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/route_lifecycle.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/route_types.go
  vendor/knative.dev/serving/pkg/apis/serving/v1alpha1/route_lifecycle.go
  vendor/knative.dev/serving/pkg/autoscaler/config/config.go
  vendor/knative.dev/serving/pkg/network/network.go
  vendor/knative.dev/serving/pkg/network/stats.go
  vendor/knative.dev/serving/test/conformance/certificate/http01/certificate.go
  vendor/knative.dev/serving/test/conformance/certificate/http01/run.go
  vendor/knative.dev/serving/test/conformance/certificate/nonhttp01/certificate.go
  vendor/knative.dev/serving/test/conformance/certificate/nonhttp01/run.go
  vendor/knative.dev/serving/test/conformance/certificate/utils.go
  vendor/knative.dev/serving/test/e2e-common.sh
  vendor/knative.dev/serving/test/e2e-tests.sh
  vendor/knative.dev/serving/test/e2e-upgrade-tests.sh
  vendor/knative.dev/serving/test/prober.go
  vendor/knative.dev/serving/test/test_images/httpproxy/service.yaml
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XL

#24 [master] Format markdown
  CONTRIBUTING.md
Labels: approved, cla: yes, lgtm, size/XS

#25 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/knative.dev/pkg/configmap/example.go
  vendor/knative.dev/pkg/configmap/store.go
  vendor/knative.dev/pkg/configmap/testing/configmap.go
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/pkg/metrics/stackdriver_exporter.go
  vendor/knative.dev/pkg/reconciler/reconcile_common.go
  vendor/knative.dev/pkg/webhook/certificates/resources/certs.go
  vendor/knative.dev/pkg/webhook/configmaps/configmaps.go
  vendor/knative.dev/pkg/webhook/webhook.go
  vendor/knative.dev/serving/pkg/apis/autoscaling/annotation_validation.go
  vendor/knative.dev/serving/pkg/apis/autoscaling/register.go
  vendor/knative.dev/serving/pkg/apis/autoscaling/v1alpha1/metric_lifecycle.go
  vendor/knative.dev/serving/pkg/apis/autoscaling/v1alpha1/pa_lifecycle.go
  vendor/knative.dev/serving/pkg/apis/autoscaling/v1alpha1/pa_types.go
  vendor/knative.dev/serving/pkg/apis/config/defaults.go
  vendor/knative.dev/serving/pkg/apis/networking/v1alpha1/certificate_lifecycle.go
  vendor/knative.dev/serving/pkg/apis/networking/v1alpha1/ingress_lifecycle.go
  vendor/knative.dev/serving/pkg/apis/networking/v1alpha1/serverlessservice_lifecycle.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/configuration_lifecycle.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/revision_helpers.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/revision_lifecycle.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/route_lifecycle.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/service_lifecycle.go
  vendor/knative.dev/serving/pkg/apis/serving/v1alpha1/revision_lifecycle.go
  vendor/knative.dev/serving/pkg/apis/serving/v1beta1/configuration_lifecycle.go
  vendor/knative.dev/serving/pkg/apis/serving/v1beta1/revision_lifecycle.go
  vendor/knative.dev/serving/pkg/apis/serving/v1beta1/route_lifecycle.go
  vendor/knative.dev/serving/pkg/apis/serving/v1beta1/service_lifecycle.go
  vendor/knative.dev/serving/test/conformance/certificate/README.md
  vendor/knative.dev/serving/test/conformance/certificate/utils.go
  vendor/knative.dev/serving/test/e2e-common.sh
  vendor/knative.dev/test-infra/scripts/library.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XL

#28 Remove unused var
  cmd/webhook/main.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/interface.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#27 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/github.com/aws/aws-sdk-go/aws/endpoints/defaults.go
  vendor/github.com/aws/aws-sdk-go/aws/version.go
  vendor/knative.dev/networking/pkg/client/injection/reconciler/networking/v1alpha1/certificate/reconciler.go
  vendor/knative.dev/pkg/leaderelection/config.go
  vendor/knative.dev/pkg/logging/config.go
  vendor/knative.dev/pkg/metrics/config_observability.go
  vendor/knative.dev/pkg/webhook/configmaps/configmaps.go
  vendor/knative.dev/serving/pkg/apis/config/features.go
  vendor/knative.dev/serving/pkg/apis/serving/fieldmask.go
  vendor/knative.dev/serving/pkg/apis/serving/k8s_validation.go
  vendor/knative.dev/serving/pkg/apis/serving/v1alpha1/revision_validation.go
  vendor/knative.dev/serving/pkg/autoscaler/config/config.go
  vendor/knative.dev/serving/pkg/network/network.go
  vendor/knative.dev/serving/pkg/network/stats.go
  vendor/knative.dev/serving/test/e2e-tests.sh
  vendor/knative.dev/serving/test/test_images/runtime/handlers/handler.go
  vendor/modules.txt
  vendor/sigs.k8s.io/yaml/.travis.yml
  vendor/sigs.k8s.io/yaml/README.md
  vendor/sigs.k8s.io/yaml/go.mod
  vendor/sigs.k8s.io/yaml/go.sum
  vendor/sigs.k8s.io/yaml/yaml.go
Labels: approved, cla: yes, lgtm, size/L

#30 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/configmap/example.go
  vendor/knative.dev/serving/pkg/apis/autoscaling/register.go
  vendor/knative.dev/test-infra/scripts/library.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#31 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/k8s.io/kube-openapi/cmd/openapi-gen/openapi-gen.go
  vendor/knative.dev/pkg/hack/tools.go
  vendor/knative.dev/pkg/metrics/config.go
  vendor/knative.dev/pkg/metrics/exporter.go
  vendor/knative.dev/pkg/metrics/prometheus_exporter.go
  vendor/knative.dev/pkg/metrics/stackdriver_exporter.go
  vendor/knative.dev/pkg/metrics/testing.go
  vendor/knative.dev/pkg/network/transports.go
  vendor/knative.dev/pkg/reconciler/reconcile_common.go
  vendor/knative.dev/pkg/test/spoof/spoof.go
  vendor/knative.dev/serving/test/cleanup.go
  vendor/knative.dev/serving/test/clients.go
  vendor/knative.dev/serving/test/conformance/certificate/http01/certificate.go
  vendor/knative.dev/serving/test/conformance/certificate/nonhttp01/certificate.go
  vendor/knative.dev/serving/test/conformance/certificate/utils.go
  vendor/knative.dev/test-infra/scripts/e2e-tests.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#29 Update README.md
  README.md
Labels: approved, cla: yes, lgtm, size/XS
