Repository knative-extensions/net-certmanager, pull requests merged in 2020-12, with the labels that each got.

#141 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/codegen-library.sh
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/hack/microbenchmarks.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#143 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/network/handlers/error.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#144 Update deps for new logging configs and logstream
  go.mod
  go.sum
  third_party/VENDOR-LICENSE/github.com/blendle/zapdriver/LICENSE
  vendor/github.com/blendle/zapdriver/.gitignore
  vendor/github.com/blendle/zapdriver/LICENSE
  vendor/github.com/blendle/zapdriver/README.md
  vendor/github.com/blendle/zapdriver/config.go
  vendor/github.com/blendle/zapdriver/core.go
  vendor/github.com/blendle/zapdriver/encoder.go
  vendor/github.com/blendle/zapdriver/go.mod
  vendor/github.com/blendle/zapdriver/go.sum
  vendor/github.com/blendle/zapdriver/http.go
  vendor/github.com/blendle/zapdriver/label.go
  vendor/github.com/blendle/zapdriver/logger.go
  vendor/github.com/blendle/zapdriver/operation.go
  vendor/github.com/blendle/zapdriver/report.go
  vendor/github.com/blendle/zapdriver/service.go
  vendor/github.com/blendle/zapdriver/source.go
  vendor/github.com/blendle/zapdriver/trace.go
  vendor/knative.dev/pkg/logging/config.go
  vendor/knative.dev/pkg/test/logstream/v2/stream.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XXL

#145 Integrate the gopath hacks
  hack/update-codegen.sh
Labels: approved, cla: yes, kind/cleanup, lgtm, size/S

#146 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/logging/config.go
  vendor/knative.dev/pkg/version/version.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#147 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/profiling/server.go
  vendor/knative.dev/pkg/test/spoof/spoof.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#148 [Automated] Update actions
  .github/workflows/knative-boilerplate.yaml
  .github/workflows/knative-donotsubmit.yaml
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-security.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: approved, cla: yes, lgtm, size/S

#149 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/leaderelection/context.go
  vendor/knative.dev/pkg/webhook/helper.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#150 Remove flaky test image
  hack/tools.go
  vendor/knative.dev/networking/test/test_images/flaky/main.go
  vendor/knative.dev/networking/test/test_images/flaky/service.yaml
  vendor/modules.txt
Labels: approved, cla: yes, kind/cleanup, lgtm, size/M

#151 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/network.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#153 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/client/injection/reconciler/networking/v1alpha1/certificate/reconciler.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/knative.dev/pkg/metrics/resource_view.go
  vendor/knative.dev/pkg/test/logstream/README.md
  vendor/knative.dev/pkg/test/logstream/interface.go
  vendor/knative.dev/pkg/test/logstream/v2/stream.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#154 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/ingress_defaults.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/ingress_types.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/ingress_validation.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#155 [Automated] Update actions
  .github/workflows/knative-style.yaml
Labels: approved, cla: yes, lgtm, size/M

#156 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/ingress_defaults.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/ingress_types.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/ingress_validation.go
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/pkg/logging/config.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#157 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/configmap/testing/configmap.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#158 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/ingress_types.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/ingress_validation.go
  vendor/knative.dev/pkg/metrics/config.go
  vendor/knative.dev/pkg/metrics/exporter.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#159 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/configmap/informer/informed_watcher.go
  vendor/knative.dev/pkg/configmap/manual_watcher.go
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/knative.dev/pkg/metrics/config_observability.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#160 [Automated] Update actions
  .github/workflows/knative-verify.yaml
Labels: approved, cla: yes, lgtm, size/XS

#162 [Automated] Update actions
  .github/workflows/knative-releasability.yaml
Labels: approved, cla: yes, lgtm, size/XS
