Repository knative-extensions/net-certmanager, pull requests merged in 2021-10, with the labels that each got.

#302 Reverting coc changes
  CODE-OF-CONDUCT.md
  code-of-conduct.md
Labels: cla: yes, approved, lgtm, size/M

#303 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/apis/contexts.go
  vendor/knative.dev/pkg/tracker/enqueue.go
  vendor/knative.dev/pkg/webhook/admission.go
  vendor/knative.dev/pkg/webhook/conversion.go
  vendor/modules.txt
Labels: cla: yes, approved, lgtm, size/M

#306 [main] Update actions
  .github/workflows/knative-go-test.yaml
Labels: cla: yes, approved, lgtm, size/XS

#311 Fix Golang 1.17 related build issues
  test/upload-test-images.sh
Labels: cla: yes, approved, lgtm, size/XS

#309 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/golang.org/x/net/http2/client_conn_pool.go
  vendor/golang.org/x/net/http2/hpack/huffman.go
  vendor/golang.org/x/net/http2/pipe.go
  vendor/golang.org/x/net/http2/server.go
  vendor/golang.org/x/net/http2/transport.go
  vendor/golang.org/x/oauth2/google/google.go
  vendor/golang.org/x/oauth2/google/internal/externalaccount/basecredentials.go
  vendor/k8s.io/gengo/examples/deepcopy-gen/generators/deepcopy.go
  vendor/k8s.io/gengo/examples/defaulter-gen/generators/defaulter.go
  vendor/k8s.io/gengo/examples/set-gen/generators/sets.go
  vendor/k8s.io/gengo/examples/set-gen/sets/byte.go
  vendor/k8s.io/gengo/examples/set-gen/sets/int.go
  vendor/k8s.io/gengo/examples/set-gen/sets/int64.go
  vendor/k8s.io/gengo/examples/set-gen/sets/string.go
  vendor/k8s.io/gengo/namer/namer.go
  vendor/k8s.io/gengo/parser/parse.go
  vendor/k8s.io/gengo/types/types.go
  vendor/knative.dev/hack/hack.go
  vendor/knative.dev/hack/infra-library.sh
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/hack/presubmit-tests.sh
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/zz_generated.deepcopy.go
  vendor/knative.dev/networking/pkg/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/apis/duck/v1/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/apis/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/hack/tools.go
  vendor/knative.dev/pkg/logging/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/metrics/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/signals/signal_posix.go
  vendor/knative.dev/pkg/tracing/config/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/tracker/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: cla: yes, size/XXL, approved, lgtm

#312 [main] Update actions
  .github/workflows/knative-releasability.yaml
Labels: cla: yes, approved, lgtm, size/XS
