Repository knative-extensions/net-certmanager, pull requests merged in 2021-06, with the labels that each got.

#225 [main] Update community files
  OWNERS_ALIASES
Labels: approved, cla: yes, lgtm, size/S

#226 [main] Update actions
  .github/workflows/knative-releasability.yaml
Labels: approved, cla: yes, lgtm, size/XS

#224 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/knative.dev/networking/test/clients.go
  vendor/knative.dev/networking/test/util.go
  vendor/knative.dev/pkg/test/README.md
  vendor/knative.dev/pkg/test/kube_checks.go
  vendor/knative.dev/pkg/webhook/certificates/resources/certs.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#227 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  third_party/VENDOR-LICENSE/github.com/evanphx/json-patch/v5/LICENSE
  vendor/github.com/evanphx/json-patch/v5/LICENSE
  vendor/github.com/evanphx/json-patch/v5/errors.go
  vendor/github.com/evanphx/json-patch/v5/go.mod
  vendor/github.com/evanphx/json-patch/v5/go.sum
  vendor/github.com/evanphx/json-patch/v5/merge.go
  vendor/github.com/evanphx/json-patch/v5/patch.go
  vendor/go.uber.org/zap/.travis.yml
  vendor/go.uber.org/zap/CHANGELOG.md
  vendor/go.uber.org/zap/CONTRIBUTING.md
  vendor/go.uber.org/zap/FAQ.md
  vendor/go.uber.org/zap/Makefile
  vendor/go.uber.org/zap/README.md
  vendor/go.uber.org/zap/field.go
  vendor/go.uber.org/zap/go.mod
  vendor/go.uber.org/zap/go.sum
  vendor/go.uber.org/zap/http_handler.go
  vendor/go.uber.org/zap/logger.go
  vendor/go.uber.org/zap/sugar.go
  vendor/go.uber.org/zap/zapcore/console_encoder.go
  vendor/go.uber.org/zap/zapcore/error.go
  vendor/go.uber.org/zap/zapcore/field.go
  vendor/go.uber.org/zap/zapcore/write_syncer.go
  vendor/gopkg.in/evanphx/json-patch.v4/.travis.yml
  vendor/gopkg.in/evanphx/json-patch.v4/README.md
  vendor/knative.dev/pkg/apis/duck/patch.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XXL

#228 Bump cert-manager to 1.3.1
  go.mod
  go.sum
  test/e2e-common.sh
  third_party/cert-manager-1.3.1/cert-manager.yaml
  third_party/cert-manager-1.3.1/download-cert-manager.sh
  vendor/github.com/aws/aws-sdk-go/aws/config.go
  vendor/github.com/aws/aws-sdk-go/aws/corehandlers/handlers.go
  vendor/github.com/aws/aws-sdk-go/aws/credentials/shared_credentials_provider.go
  vendor/github.com/aws/aws-sdk-go/aws/credentials/stscreds/web_identity_provider.go
  vendor/github.com/aws/aws-sdk-go/aws/ec2metadata/api.go
  vendor/github.com/aws/aws-sdk-go/aws/ec2metadata/service.go
  vendor/github.com/aws/aws-sdk-go/aws/endpoints/defaults.go
  vendor/github.com/aws/aws-sdk-go/aws/endpoints/v3model.go
  vendor/github.com/aws/aws-sdk-go/aws/request/connection_reset_error.go
  vendor/github.com/aws/aws-sdk-go/aws/session/doc.go
  vendor/github.com/aws/aws-sdk-go/aws/session/env_config.go
  vendor/github.com/aws/aws-sdk-go/aws/session/session.go
  vendor/github.com/aws/aws-sdk-go/aws/version.go
  vendor/github.com/aws/aws-sdk-go/private/protocol/json/jsonutil/unmarshal.go
  vendor/github.com/aws/aws-sdk-go/private/protocol/timestamp.go
  vendor/github.com/jetstack/cert-manager/LICENSES
  vendor/github.com/jetstack/cert-manager/pkg/apis/acme/doc.go
  vendor/github.com/jetstack/cert-manager/pkg/apis/acme/v1/const.go
  vendor/github.com/jetstack/cert-manager/pkg/apis/acme/v1/doc.go
  vendor/github.com/jetstack/cert-manager/pkg/apis/acme/v1/register.go
  vendor/github.com/jetstack/cert-manager/pkg/apis/acme/v1/types.go
  vendor/github.com/jetstack/cert-manager/pkg/apis/acme/v1/types_challenge.go
  vendor/github.com/jetstack/cert-manager/pkg/apis/acme/v1/types_issuer.go
  vendor/github.com/jetstack/cert-manager/pkg/apis/acme/v1/types_order.go
  vendor/github.com/jetstack/cert-manager/pkg/apis/acme/v1/zz_generated.deepcopy.go
  vendor/github.com/jetstack/cert-manager/pkg/apis/certmanager/doc.go
  vendor/github.com/jetstack/cert-manager/pkg/apis/certmanager/v1/const.go
  vendor/github.com/jetstack/cert-manager/pkg/apis/certmanager/v1/doc.go
  vendor/github.com/jetstack/cert-manager/pkg/apis/certmanager/v1/generic_issuer.go
  vendor/github.com/jetstack/cert-manager/pkg/apis/certmanager/v1/register.go
  vendor/github.com/jetstack/cert-manager/pkg/apis/certmanager/v1/types.go
  vendor/github.com/jetstack/cert-manager/pkg/apis/certmanager/v1/types_certificate.go
  vendor/github.com/jetstack/cert-manager/pkg/apis/certmanager/v1/types_certificaterequest.go
  vendor/github.com/jetstack/cert-manager/pkg/apis/certmanager/v1/types_issuer.go
  vendor/github.com/jetstack/cert-manager/pkg/apis/certmanager/v1/zz_generated.deepcopy.go
  vendor/github.com/jetstack/cert-manager/pkg/apis/meta/doc.go
  vendor/github.com/jetstack/cert-manager/pkg/apis/meta/v1/doc.go
  vendor/github.com/jetstack/cert-manager/pkg/apis/meta/v1/register.go
  vendor/github.com/jetstack/cert-manager/pkg/apis/meta/v1/types.go
  vendor/github.com/jetstack/cert-manager/pkg/apis/meta/v1/zz_generated.deepcopy.go
  vendor/github.com/jmespath/go-jmespath/.travis.yml
  vendor/github.com/jmespath/go-jmespath/Makefile
  vendor/github.com/jmespath/go-jmespath/go.mod
  vendor/github.com/jmespath/go-jmespath/go.sum
  vendor/gopkg.in/yaml.v2/.travis.yml
  vendor/gopkg.in/yaml.v2/apic.go
  vendor/gopkg.in/yaml.v2/go.mod
  vendor/gopkg.in/yaml.v2/yaml.go
  vendor/modules.txt
Labels: approved, cla: yes, kind/enhancement, lgtm, size/XXL

#229 [main] Update actions
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-vulnerability.yaml
Labels: approved, cla: yes, lgtm, size/M

#231 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/network.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#232 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/codegen-library.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#235 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/network.go
  vendor/knative.dev/pkg/webhook/configmaps/configmaps.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#236 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/.gitignore
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/2q.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/LICENSE
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/README.md
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/arc.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/doc.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/go.mod
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/lru.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/simplelru/lru.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/simplelru/lru_interface.go
  vendor/knative.dev/hack/library.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#237 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/ingress_types.go
  vendor/knative.dev/pkg/apis/duck/v1/knative_reference.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#238 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/test/environment/config.go
  vendor/knative.dev/pkg/version/version.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#239 [main] Update community files
  OWNERS_ALIASES
Labels: approved, cla: yes, lgtm, size/XS

#240 rename controller deployment for consistency
  config/controller.yaml
Labels: approved, cla: yes, lgtm, size/S

#241 rename component
  cmd/controller/main.go
Labels: approved, cla: yes, lgtm, size/XS

#242 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/network.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#244 add cert-provider label to all resources
  config/500-validating-webhook.yaml
  config/500-webhook-secret.yaml
  config/webhook-deployment.yaml
  config/webhook-service.yaml
Labels: approved, cla: yes, lgtm, size/XS

#243 use admissionregistration v1
  config/500-validating-webhook.yaml
Labels: approved, cla: yes, lgtm, size/XS

#245 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/leaderelection/config.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#247 [main] Update community files
  OWNERS_ALIASES
Labels: approved, cla: yes, lgtm, size/XS

#246 [main] Upgrade to latest dependencies
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/.gitignore
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/2q.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/LICENSE
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/README.md
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/arc.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/doc.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/go.mod
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/lru.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/simplelru/lru.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/simplelru/lru_interface.go
Labels: approved, cla: yes, lgtm, size/XS

#249 [main] Update actions
  .github/workflows/knative-go-test.yaml
Labels: approved, cla: yes, lgtm, size/XS
