Repository knative-extensions/net-certmanager, pull requests merged in 2021-11, with the labels that each got.

#320 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: cla: yes, approved, lgtm, size/M

#321 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: cla: yes, approved, lgtm, size/S

#322 Document maturity levels in sandbox
  README.md
Labels: cla: yes, approved, lgtm, size/XS

#324 [main] Update community files
  OWNERS_ALIASES
Labels: cla: yes, approved, lgtm, size/S

#325 [main] Update actions
  .github/workflows/knative-style.yaml
Labels: cla: yes, approved, lgtm, size/XS

#326 Add k8s recommended labels
  config/200-clusterrole.yaml
  config/500-validating-webhook.yaml
  config/500-webhook-secret.yaml
  config/config.yaml
  config/controller.yaml
  config/webhook-deployment.yaml
  config/webhook-service.yaml
  hack/release.sh
  test/config/200-service-account.yaml
  test/config/300-certificate.yaml
  test/config/autotls/certmanager/caissuer/config-certmanager.yaml
  test/config/autotls/certmanager/http01/config-certmanager.yaml
  test/config/autotls/certmanager/selfsigned/config-certmanager.yaml
Labels: cla: yes, approved, lgtm, size/M, kind/enhancement

#327 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/pkg/test/request.go
  vendor/modules.txt
Labels: cla: yes, approved, lgtm, size/M

#328 [main] Update actions
  .github/workflows/knative-boilerplate.yaml
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-release-notes.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: cla: yes, approved, lgtm, size/M

#329 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/knative.dev/pkg/injection/interface.go
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/modules.txt
Labels: cla: yes, approved, lgtm, size/M

#330 [main] Update community files
  OWNERS_ALIASES
Labels: cla: yes, approved, lgtm, size/XS

#331 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/apis/networking/metadata_validation.go
  vendor/knative.dev/networking/pkg/apis/networking/register.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/comment_parser.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/packages.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_controller.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_controller_stub.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/knative.dev/pkg/reconciler/filter.go
  vendor/knative.dev/pkg/test/spoof/error_checks.go
  vendor/knative.dev/pkg/test/spoof/spoof.go
  vendor/modules.txt
Labels: cla: yes, approved, lgtm, size/L

#333 [main] Update actions
  .github/workflows/knative-releasability.yaml
Labels: cla: yes, approved, lgtm, size/XS
