Repository knative-extensions/net-certmanager, pull requests merged in 2021-04, with the labels that each got.

#205 Drop --strict flag on ko
  hack/release.sh
  test/upload-test-images.sh
Labels: cla: yes, lgtm, size/XS

#207 Copy OWNERS_ALIASES from knative/community; fill in OWNERS files
  OWNERS
  OWNERS_ALIASES
  hack/OWNERS
  test/OWNERS
Labels: approved, cla: yes, lgtm, size/L

#206 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/client/injection/reconciler/networking/v1alpha1/certificate/reconciler.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#208 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/codegen-library.sh
  vendor/knative.dev/hack/presubmit-tests.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M
