Repository knative-extensions/net-certmanager, pull requests merged in 2021-12, with the labels that each got.

#332 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/knative.dev/networking/pkg/apis/networking/register.go
  vendor/knative.dev/pkg/apis/duck/v1/status_types.go
  vendor/knative.dev/pkg/configmap/parse.go
  vendor/knative.dev/pkg/kmap/lookup.go
  vendor/knative.dev/pkg/kmap/map.go
  vendor/knative.dev/pkg/kmeta/map.go
  vendor/knative.dev/pkg/metrics/config.go
  vendor/modules.txt
Labels: cla: yes, approved, lgtm, size/L

#334 [main] Update community files
  OWNERS_ALIASES
Labels: cla: yes, approved, lgtm, size/S

#336 Drop explicit indirect dependencies
  go.mod
  go.sum
  vendor/github.com/go-openapi/jsonpointer/.travis.yml
  vendor/github.com/go-openapi/jsonpointer/pointer.go
  vendor/github.com/go-openapi/jsonreference/.golangci.yml
  vendor/github.com/go-openapi/jsonreference/.travis.yml
  vendor/github.com/go-openapi/jsonreference/README.md
  vendor/github.com/go-openapi/jsonreference/go.mod
  vendor/github.com/go-openapi/jsonreference/go.sum
  vendor/github.com/go-openapi/spec/contact_info.go
  vendor/github.com/go-openapi/spec/license.go
  vendor/github.com/go-openapi/swag/.golangci.yml
  vendor/github.com/go-openapi/swag/.travis.yml
  vendor/github.com/go-openapi/swag/README.md
  vendor/github.com/go-openapi/swag/convert.go
  vendor/github.com/go-openapi/swag/convert_types.go
  vendor/github.com/go-openapi/swag/go.mod
  vendor/github.com/go-openapi/swag/go.sum
  vendor/github.com/go-openapi/swag/json.go
  vendor/github.com/go-openapi/swag/loading.go
  vendor/github.com/go-openapi/swag/util.go
  vendor/github.com/josharian/intern/README.md
  vendor/github.com/josharian/intern/go.mod
  vendor/github.com/josharian/intern/intern.go
  vendor/github.com/josharian/intern/license.md
  vendor/github.com/mailru/easyjson/buffer/pool.go
  vendor/github.com/mailru/easyjson/jlexer/lexer.go
  vendor/github.com/mailru/easyjson/jwriter/writer.go
  vendor/modules.txt
Labels: size/XXL, approved, lgtm

#337 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/github.com/rs/dnscache/.travis.yml
  vendor/github.com/rs/dnscache/LICENSE
  vendor/github.com/rs/dnscache/README.md
  vendor/github.com/rs/dnscache/dnscache.go
  vendor/github.com/rs/dnscache/go.mod
  vendor/github.com/rs/dnscache/go.sum
  vendor/golang.org/x/sync/singleflight/singleflight.go
  vendor/knative.dev/networking/test/test_images/httpproxy/httpproxy.go
  vendor/modules.txt
Labels: approved, lgtm, size/XL
