Repository knative-extensions/net-certmanager, pull requests merged in 2022-08, with the labels that each got.

#429 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, skip-review

#430 [main] Update actions
  .github/workflows/knative-releasability.yaml
Labels: approved, lgtm, size/XS, skip-review

#432 Decrease coverage target to 75 from 80
  .codecov.yaml
Labels: approved, lgtm, size/XS

#417 watch certificate in renewing state
  pkg/reconciler/certificate/certificate.go
  pkg/reconciler/certificate/certificate_test.go
  pkg/reconciler/certificate/resources/cert_manager_certificate_test.go
Labels: approved, lgtm, size/L, kind/bug

#434 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, skip-review

#433 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/network/handlers/drain.go
  vendor/modules.txt
Labels: approved, lgtm, size/M

#435 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review
