Repository knative-extensions/net-certmanager, pull requests merged in 2022-05, with the labels that each got.

#393 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/apis/deprecated.go
  vendor/knative.dev/pkg/apis/field_error.go
  vendor/modules.txt
Labels: approved, lgtm, size/L

#395 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#394 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/e2e-tests.sh
  vendor/knative.dev/pkg/apis/field_error.go
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/knative.dev/pkg/leaderelection/config.go
  vendor/knative.dev/pkg/logging/config.go
  vendor/knative.dev/pkg/network/transports.go
  vendor/modules.txt
Labels: approved, lgtm, size/L

#396 Bump cert-manager to 1.8.0
  test/e2e-common.sh
  third_party/cert-manager-1.8.0/cert-manager.yaml
  third_party/cert-manager-1.8.0/download-cert-manager.sh
Labels: approved, lgtm, size/L

#397 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#398 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#400 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#402 Add secret label for filtering informers
  go.mod
  go.sum
  pkg/reconciler/certificate/resources/cert_manager_certificate.go
  pkg/reconciler/certificate/resources/cert_manager_certificate_test.go
  vendor/knative.dev/networking/pkg/apis/networking/register.go
  vendor/modules.txt
Labels: approved, lgtm, size/S

#405 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#404 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  third_party/VENDOR-LICENSE/k8s.io/utils/internal/third_party/forked/golang/LICENSE
  vendor/k8s.io/utils/internal/third_party/forked/golang/golang-lru/lru.go
  vendor/k8s.io/utils/lru/lru.go
  vendor/knative.dev/networking/pkg/config/config.go
  vendor/knative.dev/networking/pkg/config/doc.go
  vendor/knative.dev/networking/pkg/config/zz_generated.deepcopy.go
  vendor/knative.dev/networking/pkg/deprecated_config.go
  vendor/knative.dev/networking/pkg/deprecated_header.go
  vendor/knative.dev/networking/pkg/deprecated_http.go
  vendor/knative.dev/networking/pkg/deprecated_labels.go
  vendor/knative.dev/networking/pkg/deprecated_port.go
  vendor/knative.dev/networking/pkg/http/constants.go
  vendor/knative.dev/networking/pkg/http/error.go
  vendor/knative.dev/networking/pkg/http/header/header.go
  vendor/knative.dev/networking/pkg/http/probe/handler.go
  vendor/knative.dev/networking/pkg/http/proxy/bufferpool.go
  vendor/knative.dev/networking/pkg/http/proxy/constants.go
  vendor/knative.dev/networking/pkg/http/stats/request.go
  vendor/knative.dev/networking/pkg/k8s/ports.go
  vendor/knative.dev/networking/pkg/labels/labels.go
  vendor/knative.dev/networking/test/e2e_flags.go
  vendor/knative.dev/networking/test/test_images/grpc-ping/main.go
  vendor/knative.dev/networking/test/test_images/httpproxy/httpproxy.go
  vendor/knative.dev/networking/test/test_images/runtime/handlers/handler.go
  vendor/knative.dev/networking/test/test_images/timeout/timeout.go
  vendor/knative.dev/networking/test/test_images/wsserver/echo.go
  vendor/modules.txt
Labels: size/XXL, approved, lgtm

#406 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/apis/networking/register.go
  vendor/knative.dev/networking/pkg/deprecated_config.go
  vendor/knative.dev/networking/pkg/deprecated_header.go
  vendor/knative.dev/networking/pkg/deprecated_http.go
  vendor/knative.dev/networking/pkg/deprecated_labels.go
  vendor/knative.dev/networking/pkg/labels/labels.go
  vendor/modules.txt
Labels: approved, lgtm, size/L

#407 [main] Format markdown
  CODE-OF-CONDUCT.md
Labels: approved, lgtm, size/XS

#408 [main] Update actions
  .github/workflows/knative-releasability.yaml
Labels: size/XS, skip-review

#409 fix go mod compat
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, lgtm, size/XL

#410 drop deprecated properties from knative.dev/networking
  pkg/reconciler/certificate/certificate_test.go
  pkg/reconciler/certificate/controller.go
  vendor/knative.dev/networking/pkg/deprecated_config.go
  vendor/knative.dev/networking/pkg/deprecated_header.go
  vendor/knative.dev/networking/pkg/deprecated_http.go
  vendor/knative.dev/networking/pkg/deprecated_labels.go
  vendor/knative.dev/networking/pkg/deprecated_port.go
  vendor/knative.dev/networking/pkg/http/proxy/bufferpool.go
  vendor/knative.dev/networking/pkg/http/proxy/constants.go
  vendor/knative.dev/networking/pkg/http/stats/request.go
  vendor/knative.dev/networking/pkg/k8s/ports.go
  vendor/modules.txt
Labels: approved, lgtm, size/XL

#411 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/library.sh
  vendor/modules.txt
Labels: approved, lgtm, size/S
