Repository knative-extensions/net-certmanager, pull requests merged in 2022-07, with the labels that each got.

#423 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#424 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#421 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  pkg/client/certmanager/clientset/versioned/clientset.go
  vendor/gopkg.in/yaml.v3/decode.go
  vendor/gopkg.in/yaml.v3/parserc.go
  vendor/k8s.io/api/batch/v1/types.go
  vendor/k8s.io/api/certificates/v1/types.go
  vendor/k8s.io/api/core/v1/types.go
  vendor/k8s.io/client-go/kubernetes/clientset.go
  vendor/k8s.io/client-go/pkg/version/.gitattributes
  vendor/k8s.io/client-go/tools/cache/thread_safe_store.go
  vendor/k8s.io/code-generator/cmd/client-gen/generators/generator_for_clientset.go
  vendor/knative.dev/hack/release.sh
  vendor/knative.dev/networking/config/certificate.yaml
  vendor/knative.dev/networking/config/domain-claim.yaml
  vendor/knative.dev/networking/config/domain.yaml
  vendor/knative.dev/networking/config/ingress.yaml
  vendor/knative.dev/networking/config/realm.yaml
  vendor/knative.dev/networking/config/serverlessservice.yaml
  vendor/knative.dev/networking/pkg/client/clientset/versioned/clientset.go
  vendor/knative.dev/pkg/apis/duck/v1/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/apis/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/client/injection/kube/client/client.go
  vendor/knative.dev/pkg/client/injection/kube/client/fake/fake.go
  vendor/knative.dev/pkg/client/injection/kube/informers/admissionregistration/v1/validatingwebhookconfiguration/validatingwebhookconfiguration.go
  vendor/knative.dev/pkg/client/injection/kube/informers/core/v1/service/fake/fake.go
  vendor/knative.dev/pkg/client/injection/kube/informers/core/v1/service/service.go
  vendor/knative.dev/pkg/client/injection/kube/informers/factory/factory.go
  vendor/knative.dev/pkg/client/injection/kube/informers/factory/fake/fake.go
  vendor/knative.dev/pkg/logging/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/metrics/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/tracker/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/webhook/admission.go
  vendor/modules.txt
Labels: size/XXL, approved, lgtm

#425 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/README.md
  vendor/knative.dev/pkg/apis/contexts.go
  vendor/knative.dev/pkg/changeset/commit.go
  vendor/knative.dev/pkg/changeset/doc.go
  vendor/knative.dev/pkg/hack/update-codegen.sh
  vendor/knative.dev/pkg/logging/config.go
  vendor/knative.dev/pkg/logging/logkey/constants.go
  vendor/modules.txt
Labels: approved, lgtm, size/L

#427 Bump go.mod to v1.18
  go.mod
  go.sum
Labels: approved, lgtm, size/XL

#428 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review
