Repository knative-extensions/net-certmanager, pull requests merged in 2022-02, with the labels that each got.

#350 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/modules.txt
Labels: approved, lgtm, size/M

#349 [main] Update actions
  .github/workflows/knative-release-notes.yaml
Labels: approved, lgtm, size/M

#351 Updates webhook to use app.kubernetes.io selector label
  config/500-validating-webhook.yaml
Labels: approved, lgtm, size/XS

#352 [main] Update community files
  OWNERS_ALIASES
Labels: approved, lgtm, size/XS

#354 Update `test/config/300-certificate.yaml`
  hack/tools.go
  test/config/300-certificate.yaml
  test/e2e-common.sh
  third_party/cert-manager-1.3.1/cert-manager.yaml
  third_party/cert-manager-1.7.1/cert-manager.yaml
  third_party/cert-manager-1.7.1/download-cert-manager.sh
  vendor/knative.dev/networking/config/certificate.yaml
  vendor/knative.dev/networking/config/config-network.yaml
  vendor/knative.dev/networking/config/domain-claim.yaml
  vendor/knative.dev/networking/config/domain.yaml
  vendor/knative.dev/networking/config/ingress.yaml
  vendor/knative.dev/networking/config/placeholder.go
  vendor/knative.dev/networking/config/realm.yaml
  vendor/knative.dev/networking/config/serverlessservice.yaml
  vendor/modules.txt
Labels: size/XXL, approved, lgtm

#357 Updates val webhook selector to reduce invocations
  config/500-validating-webhook.yaml
Labels: approved, lgtm, size/XS, kind/cleanup

#358 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/README.md
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/hack/release.sh
  vendor/knative.dev/networking/config/config-network.yaml
  vendor/knative.dev/networking/pkg/network.go
  vendor/modules.txt
Labels: approved, lgtm, size/M

#359 [main] Update actions
  .github/workflows/knative-style.yaml
Labels: approved, lgtm, size/XS

#360 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/apis/url.go
  vendor/knative.dev/pkg/changeset/commit.go
  vendor/modules.txt
Labels: approved, lgtm, size/M

#361 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/presubmit-tests.sh
  vendor/modules.txt
Labels: approved, lgtm, size/S

#362 [main] Update actions
  .github/workflows/knative-style.yaml
Labels: approved, lgtm, size/XS
