Repository knative-extensions/net-certmanager, pull requests merged in 2022-11, with the labels that each got.

#456 format go1.19
  pkg/client/certmanager/clientset/versioned/fake/register.go
  pkg/client/certmanager/clientset/versioned/scheme/register.go
  pkg/reconciler/certificate/config/cert_manager_test.go
  pkg/reconciler/testing/factory.go
Labels: approved, lgtm, size/XS

#454 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#453 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/README.md
  vendor/knative.dev/hack/e2e-tests.sh
  vendor/knative.dev/networking/pkg/client/clientset/versioned/fake/register.go
  vendor/knative.dev/networking/pkg/client/clientset/versioned/scheme/register.go
  vendor/knative.dev/networking/pkg/config/config.go
  vendor/knative.dev/networking/test/test_images/runtime/handlers/cgroup.go
  vendor/knative.dev/networking/test/test_images/runtime/handlers/file_access_attempt.go
  vendor/knative.dev/networking/test/test_images/wsserver/echo.go
  vendor/knative.dev/networking/test/util.go
  vendor/knative.dev/pkg/apis/duck/verify.go
  vendor/knative.dev/pkg/changeset/commit.go
  vendor/knative.dev/pkg/client/injection/kube/client/client.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/client.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/comment_parser.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/filtered_informer.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/packages.go
  vendor/knative.dev/pkg/configmap/doc.go
  vendor/knative.dev/pkg/configmap/store.go
  vendor/knative.dev/pkg/hash/doc.go
  vendor/knative.dev/pkg/injection/doc.go
  vendor/knative.dev/pkg/injection/injection.go
  vendor/knative.dev/pkg/logging/object_encoders.go
  vendor/knative.dev/pkg/metrics/prometheus_exporter.go
  vendor/knative.dev/pkg/network/h2c.go
  vendor/knative.dev/pkg/network/handlers/error.go
  vendor/knative.dev/pkg/profiling/server.go
  vendor/knative.dev/pkg/reconciler/retry.go
  vendor/knative.dev/pkg/reconciler/testing/hooks.go
  vendor/knative.dev/pkg/reconciler/testing/reactions.go
  vendor/knative.dev/pkg/reconciler/testing/sorter.go
  vendor/knative.dev/pkg/reconciler/testing/table.go
  vendor/knative.dev/pkg/test/ingress/ingress.go
  vendor/knative.dev/pkg/test/zipkin/doc.go
  vendor/knative.dev/pkg/test/zipkin/util.go
  vendor/knative.dev/pkg/webhook/webhook.go
  vendor/modules.txt
Labels: size/XXL, approved, lgtm

#461 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#462 Fix drop capabilities literal
  config/controller.yaml
  config/webhook-deployment.yaml
Labels: approved, lgtm, size/XS
