Repository knative-extensions/net-certmanager, pull requests merged in 2023-03, with the labels that each got.

#503 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: approved, lgtm, size/S

#504 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/webhook/env.go
  vendor/modules.txt
Labels: approved, lgtm, size/M

#505 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#507 [main] Update actions
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-release-notes.yaml
  .github/workflows/knative-security.yaml
  .github/workflows/knative-stale.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: size/S, skip-review

#508 Revert "Decrease coverage target to 75 from 80 (#432)"
  .codecov.yaml
Labels: approved, lgtm, size/XS

#481 followup from #214
  go.mod
  go.sum
  pkg/reconciler/certificate/certificate.go
  pkg/reconciler/certificate/certificate_test.go
  pkg/reconciler/certificate/resources/cert_manager_certificate.go
  pkg/reconciler/certificate/resources/cert_manager_certificate_test.go
  third_party/VENDOR-LICENSE/github.com/martinlindhe/base36/LICENSE
  vendor/github.com/martinlindhe/base36/LICENSE
  vendor/github.com/martinlindhe/base36/README.md
  vendor/github.com/martinlindhe/base36/base36.go
  vendor/modules.txt
Labels: approved, lgtm, size/XL

#511 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/injection/health_check.go
  vendor/knative.dev/pkg/metrics/config.go
  vendor/knative.dev/pkg/metrics/config_observability.go
  vendor/modules.txt
Labels: approved, lgtm, size/M

#510 remove common name template code
  go.mod
  pkg/reconciler/certificate/certificate_test.go
  pkg/reconciler/certificate/config/cert_manager.go
  pkg/reconciler/certificate/config/cert_manager_test.go
  pkg/reconciler/certificate/resources/cert_manager_certificate_test.go
Labels: approved, lgtm, size/L

#512 [release-1.9] pull in removal of common name template code
  go.mod
  pkg/reconciler/certificate/certificate_test.go
  pkg/reconciler/certificate/config/cert_manager.go
  pkg/reconciler/certificate/config/cert_manager_test.go
  pkg/reconciler/certificate/resources/cert_manager_certificate_test.go
Labels: approved, lgtm, size/L

#513 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/hack/presubmit-tests.sh
  vendor/modules.txt
Labels: approved, lgtm, size/S
