Repository knative-extensions/net-certmanager, pull requests merged in 2023-11, with the labels that each got.

#618 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  third_party/VENDOR-LICENSE/github.com/matttproud/golang_protobuf_extensions/v2/pbutil/LICENSE
  third_party/VENDOR-LICENSE/github.com/matttproud/golang_protobuf_extensions/v2/pbutil/NOTICE
  vendor/github.com/matttproud/golang_protobuf_extensions/v2/LICENSE
  vendor/github.com/matttproud/golang_protobuf_extensions/v2/NOTICE
  vendor/github.com/matttproud/golang_protobuf_extensions/v2/pbutil/.gitignore
  vendor/github.com/matttproud/golang_protobuf_extensions/v2/pbutil/Makefile
  vendor/github.com/matttproud/golang_protobuf_extensions/v2/pbutil/decode.go
  vendor/github.com/matttproud/golang_protobuf_extensions/v2/pbutil/doc.go
  vendor/github.com/matttproud/golang_protobuf_extensions/v2/pbutil/encode.go
  vendor/github.com/prometheus/common/expfmt/decode.go
  vendor/github.com/prometheus/common/expfmt/encode.go
  vendor/google.golang.org/grpc/README.md
  vendor/google.golang.org/grpc/attributes/attributes.go
  vendor/google.golang.org/grpc/balancer/balancer.go
  vendor/google.golang.org/grpc/clientconn.go
  vendor/google.golang.org/grpc/dialoptions.go
  vendor/google.golang.org/grpc/encoding/encoding.go
  vendor/google.golang.org/grpc/health/grpc_health_v1/health_grpc.pb.go
  vendor/google.golang.org/grpc/internal/backoff/backoff.go
  vendor/google.golang.org/grpc/internal/internal.go
  vendor/google.golang.org/grpc/internal/status/status.go
  vendor/google.golang.org/grpc/internal/transport/handler_server.go
  vendor/google.golang.org/grpc/internal/transport/http2_client.go
  vendor/google.golang.org/grpc/internal/transport/http2_server.go
  vendor/google.golang.org/grpc/internal/transport/http_util.go
  vendor/google.golang.org/grpc/internal/transport/transport.go
  vendor/google.golang.org/grpc/server.go
  vendor/google.golang.org/grpc/tap/tap.go
  vendor/google.golang.org/grpc/version.go
  vendor/google.golang.org/grpc/vet.sh
  vendor/knative.dev/hack/codegen-library.sh
  vendor/modules.txt
Labels: approved, lgtm, size/L

#620 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  pkg/client/certmanager/injection/informers/factory/filtered/fake/fake_filtered_factory.go
  pkg/client/certmanager/injection/informers/factory/filtered/filtered_factory.go
  vendor/knative.dev/hack/release.sh
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/fake_filtered_factory.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/filtered_factory.go
  vendor/modules.txt
Labels: approved, lgtm, size/M

#621 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/github.com/gorilla/websocket/.editorconfig
  vendor/github.com/gorilla/websocket/.gitignore
  vendor/github.com/gorilla/websocket/.golangci.yml
  vendor/github.com/gorilla/websocket/AUTHORS
  vendor/github.com/gorilla/websocket/LICENSE
  vendor/github.com/gorilla/websocket/Makefile
  vendor/github.com/gorilla/websocket/README.md
  vendor/github.com/gorilla/websocket/client.go
  vendor/github.com/gorilla/websocket/compression.go
  vendor/github.com/gorilla/websocket/conn.go
  vendor/github.com/gorilla/websocket/mask.go
  vendor/github.com/gorilla/websocket/proxy.go
  vendor/github.com/gorilla/websocket/server.go
  vendor/github.com/gorilla/websocket/tls_handshake.go
  vendor/github.com/gorilla/websocket/tls_handshake_116.go
  vendor/github.com/gorilla/websocket/util.go
  vendor/github.com/gorilla/websocket/x_net_proxy.go
  vendor/golang.org/x/net/internal/socks/client.go
  vendor/golang.org/x/net/internal/socks/socks.go
  vendor/golang.org/x/net/proxy/dial.go
  vendor/golang.org/x/net/proxy/direct.go
  vendor/golang.org/x/net/proxy/per_host.go
  vendor/golang.org/x/net/proxy/proxy.go
  vendor/golang.org/x/net/proxy/socks5.go
  vendor/golang.org/x/sync/errgroup/go120.go
  vendor/golang.org/x/sync/errgroup/pre_go120.go
  vendor/modules.txt
Labels: size/XXL, approved, lgtm

#624 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  third_party/VENDOR-LICENSE/go.uber.org/atomic/LICENSE.txt
  vendor/knative.dev/hack/README.md
  vendor/knative.dev/hack/codegen-library.sh
  vendor/knative.dev/hack/e2e-tests.sh
  vendor/knative.dev/hack/embed.go
  vendor/knative.dev/hack/go.work
  vendor/knative.dev/hack/go.work.sum
  vendor/knative.dev/hack/hack.go
  vendor/knative.dev/hack/infra-library.sh
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/hack/performance-tests.sh
  vendor/knative.dev/hack/presubmit-tests.sh
  vendor/knative.dev/hack/release.sh
  vendor/knative.dev/networking/config/config-network.yaml
  vendor/knative.dev/networking/pkg/apis/networking/metadata_validation.go
  vendor/knative.dev/networking/pkg/apis/networking/register.go
  vendor/knative.dev/networking/pkg/client/clientset/versioned/typed/networking/v1alpha1/fake/fake_certificate.go
  vendor/knative.dev/networking/pkg/client/clientset/versioned/typed/networking/v1alpha1/fake/fake_clusterdomainclaim.go
  vendor/knative.dev/networking/pkg/client/clientset/versioned/typed/networking/v1alpha1/fake/fake_domain.go
  vendor/knative.dev/networking/pkg/client/clientset/versioned/typed/networking/v1alpha1/fake/fake_ingress.go
  vendor/knative.dev/networking/pkg/client/clientset/versioned/typed/networking/v1alpha1/fake/fake_realm.go
  vendor/knative.dev/networking/pkg/client/clientset/versioned/typed/networking/v1alpha1/fake/fake_serverlessservice.go
  vendor/knative.dev/networking/pkg/config/config.go
  vendor/knative.dev/pkg/apis/duck/v1/addressable_types.go
  vendor/knative.dev/pkg/apis/duck/v1/destination.go
  vendor/knative.dev/pkg/apis/duck/v1/source_types.go
  vendor/knative.dev/pkg/apis/duck/v1/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/hack/update-codegen.sh
  vendor/knative.dev/pkg/metrics/metrics.go
  vendor/knative.dev/pkg/network/h2c.go
  vendor/knative.dev/pkg/network/transports.go
  vendor/knative.dev/pkg/profiling/server.go
  vendor/knative.dev/pkg/reconciler/testing/context.go
  vendor/knative.dev/pkg/reconciler/testing/hooks.go
  vendor/knative.dev/pkg/test/zipkin/util.go
  vendor/knative.dev/pkg/version/version.go
  vendor/knative.dev/pkg/webhook/helper.go
  vendor/knative.dev/pkg/webhook/webhook.go
  vendor/modules.txt
Labels: approved, lgtm, size/XL

#625 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  third_party/VENDOR-LICENSE/go.uber.org/atomic/LICENSE.txt
  vendor/knative.dev/hack/README.md
  vendor/knative.dev/hack/codegen-library.sh
  vendor/knative.dev/hack/e2e-tests.sh
  vendor/knative.dev/hack/embed.go
  vendor/knative.dev/hack/go.work
  vendor/knative.dev/hack/go.work.sum
  vendor/knative.dev/hack/infra-library.sh
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/hack/performance-tests.sh
  vendor/knative.dev/hack/presubmit-tests.sh
  vendor/knative.dev/networking/config/config-network.yaml
  vendor/knative.dev/networking/pkg/apis/networking/metadata_validation.go
  vendor/knative.dev/networking/pkg/apis/networking/register.go
  vendor/knative.dev/networking/pkg/client/clientset/versioned/typed/networking/v1alpha1/fake/fake_certificate.go
  vendor/knative.dev/networking/pkg/client/clientset/versioned/typed/networking/v1alpha1/fake/fake_clusterdomainclaim.go
  vendor/knative.dev/networking/pkg/client/clientset/versioned/typed/networking/v1alpha1/fake/fake_domain.go
  vendor/knative.dev/networking/pkg/client/clientset/versioned/typed/networking/v1alpha1/fake/fake_ingress.go
  vendor/knative.dev/networking/pkg/client/clientset/versioned/typed/networking/v1alpha1/fake/fake_realm.go
  vendor/knative.dev/networking/pkg/client/clientset/versioned/typed/networking/v1alpha1/fake/fake_serverlessservice.go
  vendor/knative.dev/networking/pkg/config/config.go
  vendor/knative.dev/pkg/apis/duck/v1/addressable_types.go
  vendor/knative.dev/pkg/apis/duck/v1/auth_types.go
  vendor/knative.dev/pkg/apis/duck/v1/destination.go
  vendor/knative.dev/pkg/apis/duck/v1/source_types.go
  vendor/knative.dev/pkg/apis/duck/v1/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/hack/update-codegen.sh
  vendor/knative.dev/pkg/metrics/metrics.go
  vendor/knative.dev/pkg/network/h2c.go
  vendor/knative.dev/pkg/network/transports.go
  vendor/knative.dev/pkg/profiling/server.go
  vendor/knative.dev/pkg/reconciler/testing/context.go
  vendor/knative.dev/pkg/reconciler/testing/hooks.go
  vendor/knative.dev/pkg/test/zipkin/util.go
  vendor/knative.dev/pkg/version/version.go
  vendor/knative.dev/pkg/webhook/helper.go
  vendor/knative.dev/pkg/webhook/webhook.go
  vendor/modules.txt
Labels: approved, lgtm, size/XL

#626 [release-1.11] Upgrade to latest dependencies
  go.mod
  go.sum
  pkg/client/certmanager/injection/informers/factory/filtered/fake/fake_filtered_factory.go
  pkg/client/certmanager/injection/informers/factory/filtered/filtered_factory.go
  vendor/knative.dev/hack/release.sh
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/fake_filtered_factory.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/filtered_factory.go
  vendor/modules.txt
Labels: approved, lgtm, size/M

#629 Make SECURITY.md consistent
  SECURITY.md
Labels: approved, lgtm, size/XS

#630 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/library.sh
  vendor/modules.txt
Labels: approved, lgtm, size/M

#631 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#632 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/apis/networking/register.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/ingress_helpers.go
  vendor/knative.dev/networking/pkg/config/config.go
  vendor/modules.txt
Labels: approved, lgtm, size/M

#636 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#635 Bump cert-manager to v1.13.2
  go.mod
  go.sum
  third_party/VENDOR-LICENSE/google.golang.org/genproto/protobuf/field_mask/LICENSE
  third_party/cert-manager-latest/cert-manager.yaml
  third_party/cert-manager-latest/download-cert-manager.sh
  vendor/github.com/cert-manager/cert-manager/LICENSES
  vendor/github.com/grpc-ecosystem/grpc-gateway/v2/internal/httprule/fuzz.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/v2/internal/httprule/parse.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/v2/runtime/context.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/v2/runtime/convert.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/v2/runtime/errors.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/v2/runtime/fieldmask.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/v2/runtime/handler.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/v2/runtime/marshal_jsonpb.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/v2/runtime/marshal_proto.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/v2/runtime/mux.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/v2/runtime/pattern.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/v2/runtime/query.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/v2/utilities/readerfactory.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/v2/utilities/trie.go
  vendor/google.golang.org/genproto/LICENSE
  vendor/google.golang.org/genproto/protobuf/field_mask/field_mask.go
  vendor/modules.txt
Labels: size/XXL, approved, lgtm

#634 Bump cert-manager to v1.13.2
  go.mod
  go.sum
  third_party/VENDOR-LICENSE/google.golang.org/genproto/protobuf/field_mask/LICENSE
  third_party/cert-manager-latest/cert-manager.yaml
  third_party/cert-manager-latest/download-cert-manager.sh
  vendor/github.com/cert-manager/cert-manager/LICENSES
  vendor/github.com/grpc-ecosystem/grpc-gateway/v2/internal/httprule/fuzz.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/v2/internal/httprule/parse.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/v2/runtime/context.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/v2/runtime/convert.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/v2/runtime/errors.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/v2/runtime/fieldmask.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/v2/runtime/handler.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/v2/runtime/marshal_jsonpb.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/v2/runtime/marshal_proto.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/v2/runtime/mux.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/v2/runtime/pattern.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/v2/runtime/query.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/v2/utilities/readerfactory.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/v2/utilities/trie.go
  vendor/google.golang.org/genproto/LICENSE
  vendor/google.golang.org/genproto/protobuf/field_mask/field_mask.go
  vendor/modules.txt
Labels: size/XXL, approved, lgtm
