Repository knative-extensions/net-certmanager, pull requests merged in 2023-07, with the labels that each got.

#538 Add the ability to create `cluster-local` certificates by an internal cert-issuer
  config/config.yaml
  config/knative-cluster-issuer.yaml
  pkg/reconciler/certificate/certificate_test.go
  pkg/reconciler/certificate/config/cert_manager.go
  pkg/reconciler/certificate/config/cert_manager_test.go
  pkg/reconciler/certificate/config/store_test.go
  pkg/reconciler/certificate/resources/cert_manager_certificate.go
  pkg/reconciler/certificate/resources/cert_manager_certificate_test.go
  test/e2e-common.sh
  test/e2e-tests.sh
Labels: approved, lgtm, size/L, kind/enhancement

#555 read buildinfo go runtime vs ko
  cmd/controller/kodata/HEAD
  cmd/controller/kodata/refs
  cmd/webhook/kodata/HEAD
  cmd/webhook/kodata/refs
Labels: approved, lgtm, size/XS

#558 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#559 Add copyright to `config/knative-cluster-issuer.yaml`
  config/knative-cluster-issuer.yaml
Labels: approved, lgtm, size/S

#560 Add common labels to the Knative cluster issuer resources
  config/knative-cluster-issuer.yaml
Labels: approved, lgtm, size/S, kind/cleanup

#551 go back to using short prefix on domain
  go.mod
  go.sum
  pkg/reconciler/certificate/certificate.go
  pkg/reconciler/certificate/certificate_test.go
  pkg/reconciler/certificate/resources/cert_manager_certificate.go
  pkg/reconciler/certificate/resources/cert_manager_certificate_test.go
  third_party/VENDOR-LICENSE/github.com/martinlindhe/base36/LICENSE
  vendor/github.com/martinlindhe/base36/LICENSE
  vendor/github.com/martinlindhe/base36/README.md
  vendor/github.com/martinlindhe/base36/base36.go
  vendor/modules.txt
Labels: approved, lgtm, size/L, kind/enhancement

#561 [release-1.10] go back to using short prefix on domain (#551)
  go.mod
  go.sum
  pkg/reconciler/certificate/certificate.go
  pkg/reconciler/certificate/certificate_test.go
  pkg/reconciler/certificate/resources/cert_manager_certificate.go
  pkg/reconciler/certificate/resources/cert_manager_certificate_test.go
  third_party/VENDOR-LICENSE/github.com/martinlindhe/base36/LICENSE
  vendor/github.com/martinlindhe/base36/LICENSE
  vendor/github.com/martinlindhe/base36/README.md
  vendor/github.com/martinlindhe/base36/base36.go
  vendor/modules.txt
Labels: approved, lgtm, size/L

#562 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, lgtm, size/S
