Repository knative-extensions/net-certmanager, pull requests merged in 2023-01, with the labels that each got.

#471 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/presubmit-tests.sh
  vendor/knative.dev/hack/release.sh
  vendor/knative.dev/pkg/kmeta/names.go
  vendor/knative.dev/pkg/test/logstream/interface.go
  vendor/knative.dev/pkg/test/logstream/v2/stream.go
  vendor/modules.txt
Labels: approved, lgtm, size/L

#474 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, skip-review

#475 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/config/certificate.yaml
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/certificate_types.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/certificate_validation.go
  vendor/modules.txt
Labels: approved, lgtm, size/M

#477 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/certificate_validation.go
  vendor/modules.txt
Labels: approved, lgtm, size/S

#457 Make the webhook port number configurable
  cmd/webhook/main.go
  config/webhook-deployment.yaml
  config/webhook-service.yaml
Labels: approved, lgtm, size/S, ok-to-test

#479 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#478 Rebased #472: Set Certificate.Spec.Domain as commonName
  go.mod
  go.sum
  pkg/reconciler/certificate/certificate.go
  pkg/reconciler/certificate/certificate_test.go
  pkg/reconciler/certificate/config/cert_manager.go
  pkg/reconciler/certificate/config/cert_manager_test.go
  pkg/reconciler/certificate/resources/cert_manager_certificate.go
  pkg/reconciler/certificate/resources/cert_manager_certificate_test.go
  third_party/go.mod
  vendor/knative.dev/networking/test/conformance/certificate/http01/certificate.go
  vendor/modules.txt
Labels: approved, lgtm, size/L
