Repository knative-extensions/net-certmanager, pull requests merged in 2023-05, with the labels that each got.

#527 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#528 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/config/config-network.yaml
  vendor/knative.dev/networking/pkg/config/config.go
  vendor/knative.dev/pkg/apis/duck/v1/source_types.go
  vendor/knative.dev/pkg/apis/duck/v1/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: approved, lgtm, size/L

#529 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/config/config.go
  vendor/modules.txt
Labels: approved, lgtm, size/S

#530 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/config/config.go
  vendor/modules.txt
Labels: approved, lgtm, size/S

#533 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#536 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#535 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/client/clientset/versioned/clientset.go
  vendor/knative.dev/networking/pkg/client/informers/externalversions/factory.go
  vendor/modules.txt
Labels: approved, lgtm, size/M

#537 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/webhook/webhook.go
  vendor/modules.txt
Labels: approved, lgtm, size/M

#540 drop safe-to-evict annotations
  config/controller.yaml
  config/webhook-deployment.yaml
Labels: approved, lgtm, size/XS

#541 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/injection/clients.go
  vendor/knative.dev/pkg/injection/informers.go
  vendor/knative.dev/pkg/injection/interface.go
  vendor/modules.txt
Labels: approved, lgtm, size/M
