Repository knative-extensions/net-certmanager, pull requests merged in 2023-09, with the labels that each got.

#578 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#579 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/hack/update-codegen.sh
  vendor/modules.txt
Labels: approved, lgtm, size/S

#580 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/apis/duck/v1/addressable_types.go
  vendor/knative.dev/pkg/apis/duck/v1/destination.go
  vendor/knative.dev/pkg/apis/duck/v1/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: approved, lgtm, size/S

#581 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/embed.go
  vendor/knative.dev/hack/go.work
  vendor/knative.dev/hack/go.work.sum
  vendor/knative.dev/hack/infra-library.sh
  vendor/knative.dev/hack/library.sh
  vendor/modules.txt
Labels: approved, lgtm, size/M

#584 add seccompProfile to controller and webhook
  config/controller.yaml
  config/webhook-deployment.yaml
Labels: approved, lgtm, size/XS

#586 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#587 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/config/config-network.yaml
  vendor/modules.txt
Labels: approved, lgtm, size/M

#589 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#590 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  third_party/VENDOR-LICENSE/github.com/benbjohnson/clock/LICENSE
  vendor/github.com/benbjohnson/clock/LICENSE
  vendor/github.com/benbjohnson/clock/README.md
  vendor/github.com/benbjohnson/clock/clock.go
  vendor/github.com/benbjohnson/clock/context.go
  vendor/github.com/evanphx/json-patch/v5/patch.go
  vendor/go.uber.org/zap/.golangci.yml
  vendor/go.uber.org/zap/CHANGELOG.md
  vendor/go.uber.org/zap/Makefile
  vendor/go.uber.org/zap/array.go
  vendor/go.uber.org/zap/array_go118.go
  vendor/go.uber.org/zap/buffer/buffer.go
  vendor/go.uber.org/zap/error.go
  vendor/go.uber.org/zap/field.go
  vendor/go.uber.org/zap/http_handler.go
  vendor/go.uber.org/zap/internal/stacktrace/stack.go
  vendor/go.uber.org/zap/internal/ztest/clock.go
  vendor/go.uber.org/zap/logger.go
  vendor/go.uber.org/zap/sink.go
  vendor/go.uber.org/zap/writer.go
  vendor/go.uber.org/zap/zapcore/core.go
  vendor/go.uber.org/zap/zapcore/entry.go
  vendor/go.uber.org/zap/zapcore/error.go
  vendor/go.uber.org/zap/zapcore/json_encoder.go
  vendor/go.uber.org/zap/zapcore/lazy_with.go
  vendor/google.golang.org/grpc/call.go
  vendor/google.golang.org/grpc/clientconn.go
  vendor/google.golang.org/grpc/stream.go
  vendor/google.golang.org/grpc/version.go
  vendor/modules.txt
Labels: size/XXL, approved, lgtm

#592 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/library.sh
  vendor/modules.txt
Labels: approved, lgtm, size/S

#591 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#595 Bump cert-manager to v11.5
  go.mod
  go.sum
  test/e2e-common.sh
  third_party/VENDOR-LICENSE/sigs.k8s.io/gateway-api/apis/v1beta1/LICENSE
  third_party/cert-manager-1.11.5/cert-manager.yaml
  third_party/cert-manager-1.11.5/download-cert-manager.sh
  vendor/github.com/cert-manager/cert-manager/LICENSES
  vendor/github.com/cert-manager/cert-manager/pkg/apis/acme/v1/types_issuer.go
  vendor/github.com/cert-manager/cert-manager/pkg/apis/acme/v1/zz_generated.deepcopy.go
  vendor/github.com/cert-manager/cert-manager/pkg/apis/certmanager/v1/types.go
  vendor/github.com/cert-manager/cert-manager/pkg/apis/certmanager/v1/types_certificate.go
  vendor/github.com/cert-manager/cert-manager/pkg/apis/certmanager/v1/types_issuer.go
  vendor/github.com/cert-manager/cert-manager/pkg/apis/certmanager/v1/zz_generated.deepcopy.go
  vendor/github.com/evanphx/json-patch/patch.go
  vendor/github.com/google/gnostic/jsonschema/display.go
  vendor/github.com/google/gnostic/jsonschema/models.go
  vendor/github.com/google/gnostic/jsonschema/reader.go
  vendor/github.com/google/gnostic/jsonschema/writer.go
  vendor/github.com/google/gnostic/openapiv2/OpenAPIv2.go
  vendor/github.com/google/gnostic/openapiv3/OpenAPIv3.go
  vendor/github.com/google/gnostic/openapiv3/OpenAPIv3.pb.go
  vendor/github.com/google/gnostic/openapiv3/OpenAPIv3.proto
  vendor/github.com/google/gnostic/openapiv3/README.md
  vendor/github.com/google/gnostic/openapiv3/annotations.pb.go
  vendor/github.com/google/gnostic/openapiv3/annotations.proto
  vendor/k8s.io/kube-openapi/pkg/common/common.go
  vendor/k8s.io/kube-openapi/pkg/generators/enum.go
  vendor/k8s.io/kube-openapi/pkg/generators/rules/names_match.go
  vendor/k8s.io/kube-openapi/pkg/handler3/handler.go
  vendor/k8s.io/kube-openapi/pkg/internal/third_party/go-json-experiment/json/doc.go
  vendor/k8s.io/kube-openapi/pkg/spec3/example.go
  vendor/k8s.io/kube-openapi/pkg/spec3/external_documentation.go
  vendor/k8s.io/kube-openapi/pkg/spec3/media_type.go
  vendor/k8s.io/kube-openapi/pkg/spec3/operation.go
  vendor/k8s.io/kube-openapi/pkg/spec3/path.go
  vendor/k8s.io/kube-openapi/pkg/spec3/request_body.go
  vendor/k8s.io/kube-openapi/pkg/spec3/response.go
  vendor/k8s.io/kube-openapi/pkg/spec3/security_requirement.go
  vendor/k8s.io/kube-openapi/pkg/spec3/security_scheme.go
  vendor/k8s.io/kube-openapi/pkg/spec3/server.go
  vendor/k8s.io/kube-openapi/pkg/validation/spec/paths.go
  vendor/k8s.io/utils/net/ipfamily.go
  vendor/k8s.io/utils/net/net.go
  vendor/k8s.io/utils/net/port.go
  vendor/modules.txt
  vendor/sigs.k8s.io/gateway-api/apis/v1alpha2/policy_types.go
  vendor/sigs.k8s.io/gateway-api/apis/v1alpha2/tcproute_types.go
  vendor/sigs.k8s.io/gateway-api/apis/v1alpha2/tlsroute_types.go
  vendor/sigs.k8s.io/gateway-api/apis/v1alpha2/udproute_types.go
  vendor/sigs.k8s.io/gateway-api/apis/v1beta1/doc.go
  vendor/sigs.k8s.io/gateway-api/apis/v1beta1/gateway_types.go
  vendor/sigs.k8s.io/gateway-api/apis/v1beta1/gatewayclass_types.go
  vendor/sigs.k8s.io/gateway-api/apis/v1beta1/httproute_types.go
  vendor/sigs.k8s.io/gateway-api/apis/v1beta1/object_reference_types.go
  vendor/sigs.k8s.io/gateway-api/apis/v1beta1/referencegrant_types.go
  vendor/sigs.k8s.io/gateway-api/apis/v1beta1/shared_types.go
  vendor/sigs.k8s.io/gateway-api/apis/v1beta1/zz_generated.deepcopy.go
  vendor/sigs.k8s.io/gateway-api/apis/v1beta1/zz_generated.register.go
Labels: size/XXL, approved, lgtm

#593 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, skip-review

#599 Bump cert-manager manifest to 1.13.0
  test/e2e-common.sh
  third_party/cert-manager-latest/cert-manager.yaml
  third_party/cert-manager-latest/download-cert-manager.sh
Labels: approved, lgtm, size/L
